libraries/time_dist-install_VERSION = 1.2.0.3
libraries/time_dist-install_MODULES = Data.Time.Calendar Data.Time.Calendar.MonthDay Data.Time.Calendar.OrdinalDate Data.Time.Calendar.WeekDate Data.Time.Calendar.Julian Data.Time.Calendar.Easter Data.Time.Clock Data.Time.Clock.POSIX Data.Time.Clock.TAI Data.Time.LocalTime Data.Time.Format Data.Time Data.Time.Calendar.Private Data.Time.Calendar.Days Data.Time.Calendar.Gregorian Data.Time.Calendar.JulianYearDay Data.Time.Clock.Scale Data.Time.Clock.UTC Data.Time.Clock.CTimeval Data.Time.Clock.UTCDiff Data.Time.LocalTime.TimeZone Data.Time.LocalTime.TimeOfDay Data.Time.LocalTime.LocalTime Data.Time.Format.Parse
libraries/time_dist-install_HIDDEN_MODULES = Data.Time.Calendar.Private Data.Time.Calendar.Days Data.Time.Calendar.Gregorian Data.Time.Calendar.JulianYearDay Data.Time.Clock.Scale Data.Time.Clock.UTC Data.Time.Clock.CTimeval Data.Time.Clock.UTCDiff Data.Time.LocalTime.TimeZone Data.Time.LocalTime.TimeOfDay Data.Time.LocalTime.LocalTime Data.Time.Format.Parse
libraries/time_dist-install_SYNOPSIS =A time library
libraries/time_dist-install_HS_SRC_DIRS = .
libraries/time_dist-install_DEPS = base-4.3.1.0 old-locale-1.0.0.2
libraries/time_dist-install_DEP_NAMES = base old-locale
libraries/time_dist-install_INCLUDE_DIRS = include
libraries/time_dist-install_INCLUDES = 
libraries/time_dist-install_INSTALL_INCLUDES = HsTime.h HsTimeConfig.h
libraries/time_dist-install_EXTRA_LIBRARIES = 
libraries/time_dist-install_EXTRA_LIBDIRS = 
libraries/time_dist-install_C_SRCS  = cbits/HsTime.c
libraries/time_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/time/cbits/*.cmm)))
libraries/time_dist-install_DATA_FILES = 
libraries/time_dist-install_HC_OPTS = -Wall -XRank2Types -XDeriveDataTypeable -XStandaloneDeriving -XForeignFunctionInterface -XCPP
libraries/time_dist-install_CC_OPTS = 
libraries/time_dist-install_CPP_OPTS = -DLANGUAGE_Rank2Types -DLANGUAGE_DeriveDataTypeable -DLANGUAGE_StandaloneDeriving
libraries/time_dist-install_LD_OPTS = 
libraries/time_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/time_dist-install_DEP_CC_OPTS = 
libraries/time_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-locale/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/time_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/time_dist-install_DEP_LD_OPTS = 
libraries/time_dist-install_BUILD_GHCI_LIB = YES
