libraries/array_dist-install_VERSION = 0.3.0.2
libraries/array_dist-install_MODULES = Data.Array.Base Data.Array.IArray Data.Array.IO Data.Array.IO.Internals Data.Array.MArray Data.Array.ST Data.Array.Storable Data.Array.Unboxed Data.Array
libraries/array_dist-install_HIDDEN_MODULES = 
libraries/array_dist-install_SYNOPSIS =Mutable and immutable arrays
libraries/array_dist-install_HS_SRC_DIRS = .
libraries/array_dist-install_DEPS = base-4.3.1.0
libraries/array_dist-install_DEP_NAMES = base
libraries/array_dist-install_INCLUDE_DIRS = include
libraries/array_dist-install_INCLUDES = 
libraries/array_dist-install_INSTALL_INCLUDES = 
libraries/array_dist-install_EXTRA_LIBRARIES = 
libraries/array_dist-install_EXTRA_LIBDIRS = 
libraries/array_dist-install_C_SRCS  = 
libraries/array_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/array/cbits/*.cmm)))
libraries/array_dist-install_DATA_FILES = 
libraries/array_dist-install_HC_OPTS = -XMultiParamTypeClasses -XFlexibleContexts -XFlexibleInstances -XTypeSynonymInstances -XRank2Types -XMagicHash -XUnboxedTuples -XForeignFunctionInterface -XUnliftedFFITypes -XCPP
libraries/array_dist-install_CC_OPTS = 
libraries/array_dist-install_CPP_OPTS = 
libraries/array_dist-install_LD_OPTS = 
libraries/array_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/array_dist-install_DEP_CC_OPTS = 
libraries/array_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/array_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/array_dist-install_DEP_LD_OPTS = 
libraries/array_dist-install_BUILD_GHCI_LIB = YES
