libraries/process_dist-install_VERSION = 1.0.1.5
libraries/process_dist-install_MODULES = System.Process.Internals System.Process System.Cmd
libraries/process_dist-install_HIDDEN_MODULES = 
libraries/process_dist-install_SYNOPSIS =Process libraries
libraries/process_dist-install_HS_SRC_DIRS = .
libraries/process_dist-install_DEPS = base-4.3.1.0 directory-1.1.0.0 filepath-1.2.0.0 unix-2.4.2.0
libraries/process_dist-install_DEP_NAMES = base directory filepath unix
libraries/process_dist-install_INCLUDE_DIRS = include
libraries/process_dist-install_INCLUDES = runProcess.h
libraries/process_dist-install_INSTALL_INCLUDES = runProcess.h HsProcessConfig.h
libraries/process_dist-install_EXTRA_LIBRARIES = 
libraries/process_dist-install_EXTRA_LIBDIRS = 
libraries/process_dist-install_C_SRCS  = cbits/runProcess.c
libraries/process_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/process/cbits/*.cmm)))
libraries/process_dist-install_DATA_FILES = 
libraries/process_dist-install_HC_OPTS = -XCPP
libraries/process_dist-install_CC_OPTS = 
libraries/process_dist-install_CPP_OPTS = -Dbase4
libraries/process_dist-install_LD_OPTS = 
libraries/process_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/process_dist-install_DEP_CC_OPTS = 
libraries/process_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-locale/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/filepath/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/process_dist-install_DEP_EXTRA_LIBS = rt util dl pthread gmp m rt dl
libraries/process_dist-install_DEP_LD_OPTS = 
libraries/process_dist-install_BUILD_GHCI_LIB = YES
