libraries/integer-gmp_dist-install_VERSION = 0.2.0.3
libraries/integer-gmp_dist-install_MODULES = GHC.Integer GHC.Integer.GMP.Internals GHC.Integer.Type
libraries/integer-gmp_dist-install_HIDDEN_MODULES = GHC.Integer.Type
libraries/integer-gmp_dist-install_SYNOPSIS =Integer library based on GMP
libraries/integer-gmp_dist-install_HS_SRC_DIRS = .
libraries/integer-gmp_dist-install_DEPS = ghc-prim-0.2.0.0
libraries/integer-gmp_dist-install_DEP_NAMES = ghc-prim
libraries/integer-gmp_dist-install_INCLUDE_DIRS = 
libraries/integer-gmp_dist-install_INCLUDES = 
libraries/integer-gmp_dist-install_INSTALL_INCLUDES = 
libraries/integer-gmp_dist-install_EXTRA_LIBRARIES = gmp
libraries/integer-gmp_dist-install_EXTRA_LIBDIRS = 
libraries/integer-gmp_dist-install_C_SRCS  = cbits/cbits.c
libraries/integer-gmp_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/integer-gmp/cbits/*.cmm)))
libraries/integer-gmp_dist-install_DATA_FILES = 
libraries/integer-gmp_dist-install_HC_OPTS = -package-name integer-gmp -XCPP -XMagicHash -XUnboxedTuples -XNoImplicitPrelude -XForeignFunctionInterface -XUnliftedFFITypes
libraries/integer-gmp_dist-install_CC_OPTS = 
libraries/integer-gmp_dist-install_CPP_OPTS = 
libraries/integer-gmp_dist-install_LD_OPTS = 
libraries/integer-gmp_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/integer-gmp_dist-install_DEP_CC_OPTS = 
libraries/integer-gmp_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/integer-gmp_dist-install_DEP_EXTRA_LIBS = m rt dl
libraries/integer-gmp_dist-install_DEP_LD_OPTS = 
libraries/integer-gmp_dist-install_BUILD_GHCI_LIB = YES
