libraries/hpc_dist-install_VERSION = 0.5.0.6
libraries/hpc_dist-install_MODULES = Trace.Hpc.Util Trace.Hpc.Mix Trace.Hpc.Tix Trace.Hpc.Reflect
libraries/hpc_dist-install_HIDDEN_MODULES = 
libraries/hpc_dist-install_SYNOPSIS =Code Coverage Library for Haskell
libraries/hpc_dist-install_HS_SRC_DIRS = .
libraries/hpc_dist-install_DEPS = base-4.3.1.0 containers-0.4.0.0 directory-1.1.0.0 old-time-1.0.0.6
libraries/hpc_dist-install_DEP_NAMES = base containers directory old-time
libraries/hpc_dist-install_INCLUDE_DIRS = 
libraries/hpc_dist-install_INCLUDES = 
libraries/hpc_dist-install_INSTALL_INCLUDES = 
libraries/hpc_dist-install_EXTRA_LIBRARIES = 
libraries/hpc_dist-install_EXTRA_LIBDIRS = 
libraries/hpc_dist-install_C_SRCS  = 
libraries/hpc_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/hpc/cbits/*.cmm)))
libraries/hpc_dist-install_DATA_FILES = 
libraries/hpc_dist-install_HC_OPTS = -Wall -XCPP
libraries/hpc_dist-install_CC_OPTS = 
libraries/hpc_dist-install_CPP_OPTS = 
libraries/hpc_dist-install_LD_OPTS = 
libraries/hpc_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/hpc_dist-install_DEP_CC_OPTS = 
libraries/hpc_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-locale/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/filepath/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/hpc_dist-install_DEP_EXTRA_LIBS = rt util dl pthread gmp m rt dl
libraries/hpc_dist-install_DEP_LD_OPTS = 
libraries/hpc_dist-install_BUILD_GHCI_LIB = YES
