libraries/old-time_dist-install_VERSION = 1.0.0.6
libraries/old-time_dist-install_MODULES = System.Time
libraries/old-time_dist-install_HIDDEN_MODULES = 
libraries/old-time_dist-install_SYNOPSIS =Time library
libraries/old-time_dist-install_HS_SRC_DIRS = .
libraries/old-time_dist-install_DEPS = base-4.3.1.0 old-locale-1.0.0.2
libraries/old-time_dist-install_DEP_NAMES = base old-locale
libraries/old-time_dist-install_INCLUDE_DIRS = include
libraries/old-time_dist-install_INCLUDES = HsTime.h
libraries/old-time_dist-install_INSTALL_INCLUDES = HsTime.h HsTimeConfig.h
libraries/old-time_dist-install_EXTRA_LIBRARIES = 
libraries/old-time_dist-install_EXTRA_LIBDIRS = 
libraries/old-time_dist-install_C_SRCS  = cbits/timeUtils.c
libraries/old-time_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/old-time/cbits/*.cmm)))
libraries/old-time_dist-install_DATA_FILES = 
libraries/old-time_dist-install_HC_OPTS = -XCPP -XForeignFunctionInterface
libraries/old-time_dist-install_CC_OPTS = 
libraries/old-time_dist-install_CPP_OPTS = 
libraries/old-time_dist-install_LD_OPTS = 
libraries/old-time_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/old-time_dist-install_DEP_CC_OPTS = 
libraries/old-time_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-locale/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/old-time_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/old-time_dist-install_DEP_LD_OPTS = 
libraries/old-time_dist-install_BUILD_GHCI_LIB = YES
