libraries/extensible-exceptions_dist-install_VERSION = 0.1.1.2
libraries/extensible-exceptions_dist-install_MODULES = Control.Exception.Extensible
libraries/extensible-exceptions_dist-install_HIDDEN_MODULES = 
libraries/extensible-exceptions_dist-install_SYNOPSIS =Extensible exceptions
libraries/extensible-exceptions_dist-install_HS_SRC_DIRS = .
libraries/extensible-exceptions_dist-install_DEPS = base-4.3.1.0
libraries/extensible-exceptions_dist-install_DEP_NAMES = base
libraries/extensible-exceptions_dist-install_INCLUDE_DIRS = 
libraries/extensible-exceptions_dist-install_INCLUDES = 
libraries/extensible-exceptions_dist-install_INSTALL_INCLUDES = 
libraries/extensible-exceptions_dist-install_EXTRA_LIBRARIES = 
libraries/extensible-exceptions_dist-install_EXTRA_LIBDIRS = 
libraries/extensible-exceptions_dist-install_C_SRCS  = 
libraries/extensible-exceptions_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/extensible-exceptions/cbits/*.cmm)))
libraries/extensible-exceptions_dist-install_DATA_FILES = 
libraries/extensible-exceptions_dist-install_HC_OPTS = -XCPP -XExistentialQuantification -XDeriveDataTypeable
libraries/extensible-exceptions_dist-install_CC_OPTS = 
libraries/extensible-exceptions_dist-install_CPP_OPTS = -DUSE_NEW_EXCEPTIONS
libraries/extensible-exceptions_dist-install_LD_OPTS = 
libraries/extensible-exceptions_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/extensible-exceptions_dist-install_DEP_CC_OPTS = 
libraries/extensible-exceptions_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/extensible-exceptions_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/extensible-exceptions_dist-install_DEP_LD_OPTS = 
libraries/extensible-exceptions_dist-install_BUILD_GHCI_LIB = YES
