libraries/utf8-string_dist-install_VERSION = 0.3.6
libraries/utf8-string_dist-install_MODULES = Codec.Binary.UTF8.String Codec.Binary.UTF8.Generic System.IO.UTF8 System.Environment.UTF8 Data.String.UTF8 Data.ByteString.UTF8 Data.ByteString.Lazy.UTF8
libraries/utf8-string_dist-install_HIDDEN_MODULES = 
libraries/utf8-string_dist-install_SYNOPSIS =Support for reading and writing UTF8 Strings
libraries/utf8-string_dist-install_HS_SRC_DIRS = .
libraries/utf8-string_dist-install_DEPS = base-4.3.1.0 bytestring-0.9.1.10
libraries/utf8-string_dist-install_DEP_NAMES = base bytestring
libraries/utf8-string_dist-install_INCLUDE_DIRS = 
libraries/utf8-string_dist-install_INCLUDES = 
libraries/utf8-string_dist-install_INSTALL_INCLUDES = 
libraries/utf8-string_dist-install_EXTRA_LIBRARIES = 
libraries/utf8-string_dist-install_EXTRA_LIBDIRS = 
libraries/utf8-string_dist-install_C_SRCS  = 
libraries/utf8-string_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/utf8-string/cbits/*.cmm)))
libraries/utf8-string_dist-install_DATA_FILES = 
libraries/utf8-string_dist-install_HC_OPTS = -W -O2 -XCPP
libraries/utf8-string_dist-install_CC_OPTS = 
libraries/utf8-string_dist-install_CPP_OPTS = 
libraries/utf8-string_dist-install_LD_OPTS = 
libraries/utf8-string_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/bytestring/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/utf8-string_dist-install_DEP_CC_OPTS = 
libraries/utf8-string_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/bytestring/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/utf8-string_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/utf8-string_dist-install_DEP_LD_OPTS = 
libraries/utf8-string_dist-install_BUILD_GHCI_LIB = YES
