libraries/ghc-binary_dist-install_VERSION = 0.5.0.2
libraries/ghc-binary_dist-install_MODULES = Data.Binary Data.Binary.Put Data.Binary.Get Data.Binary.Builder
libraries/ghc-binary_dist-install_HIDDEN_MODULES = 
libraries/ghc-binary_dist-install_SYNOPSIS =Binary serialisation for Haskell values using lazy ByteStrings
libraries/ghc-binary_dist-install_HS_SRC_DIRS = src
libraries/ghc-binary_dist-install_DEPS = array-0.3.0.2 base-4.3.1.0 bytestring-0.9.1.10 containers-0.4.0.0
libraries/ghc-binary_dist-install_DEP_NAMES = array base bytestring containers
libraries/ghc-binary_dist-install_INCLUDE_DIRS = 
libraries/ghc-binary_dist-install_INCLUDES = 
libraries/ghc-binary_dist-install_INSTALL_INCLUDES = 
libraries/ghc-binary_dist-install_EXTRA_LIBRARIES = 
libraries/ghc-binary_dist-install_EXTRA_LIBDIRS = 
libraries/ghc-binary_dist-install_C_SRCS  = 
libraries/ghc-binary_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/ghc-binary/cbits/*.cmm)))
libraries/ghc-binary_dist-install_DATA_FILES = 
libraries/ghc-binary_dist-install_HC_OPTS = -O2 -Wall -fliberate-case-threshold=1000 -XCPP -XFlexibleContexts
libraries/ghc-binary_dist-install_CC_OPTS = 
libraries/ghc-binary_dist-install_CPP_OPTS = -DAPPLICATIVE_IN_BASE
libraries/ghc-binary_dist-install_LD_OPTS = 
libraries/ghc-binary_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/bytestring/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/ghc-binary_dist-install_DEP_CC_OPTS = 
libraries/ghc-binary_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/bytestring/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/ghc-binary_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/ghc-binary_dist-install_DEP_LD_OPTS = 
libraries/ghc-binary_dist-install_BUILD_GHCI_LIB = YES
