libraries/unix_dist-install_VERSION = 2.4.2.0
libraries/unix_dist-install_MODULES = System.Posix System.Posix.DynamicLinker.Module System.Posix.DynamicLinker.Prim System.Posix.Directory System.Posix.DynamicLinker System.Posix.Env System.Posix.Error System.Posix.Files System.Posix.IO System.Posix.Process System.Posix.Process.Internals System.Posix.Resource System.Posix.Temp System.Posix.Terminal System.Posix.Time System.Posix.Unistd System.Posix.User System.Posix.Signals System.Posix.Signals.Exts System.Posix.Semaphore System.Posix.SharedMem
libraries/unix_dist-install_HIDDEN_MODULES = 
libraries/unix_dist-install_SYNOPSIS =POSIX functionality
libraries/unix_dist-install_HS_SRC_DIRS = .
libraries/unix_dist-install_DEPS = base-4.3.1.0
libraries/unix_dist-install_DEP_NAMES = base
libraries/unix_dist-install_INCLUDE_DIRS = include
libraries/unix_dist-install_INCLUDES = HsUnix.h execvpe.h
libraries/unix_dist-install_INSTALL_INCLUDES = HsUnix.h HsUnixConfig.h execvpe.h
libraries/unix_dist-install_EXTRA_LIBRARIES = rt util dl pthread
libraries/unix_dist-install_EXTRA_LIBDIRS = 
libraries/unix_dist-install_C_SRCS  = cbits/HsUnix.c cbits/execvpe.c cbits/dirUtils.c
libraries/unix_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/unix/cbits/*.cmm)))
libraries/unix_dist-install_DATA_FILES = 
libraries/unix_dist-install_HC_OPTS = -XCPP -XForeignFunctionInterface -XEmptyDataDecls
libraries/unix_dist-install_CC_OPTS = 
libraries/unix_dist-install_CPP_OPTS = 
libraries/unix_dist-install_LD_OPTS = 
libraries/unix_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/unix_dist-install_DEP_CC_OPTS = 
libraries/unix_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/unix_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/unix_dist-install_DEP_LD_OPTS = 
libraries/unix_dist-install_BUILD_GHCI_LIB = YES
