libraries/base_dist-install_VERSION = 4.3.1.0
libraries/base_dist-install_MODULES = Foreign.Concurrent GHC.Arr GHC.Base GHC.Classes GHC.Conc GHC.Conc.IO GHC.Conc.Signal GHC.Conc.Sync GHC.ConsoleHandler GHC.Constants GHC.Desugar GHC.Enum GHC.Environment GHC.Err GHC.Exception GHC.Exts GHC.Float GHC.ForeignPtr GHC.MVar GHC.IO GHC.IO.IOMode GHC.IO.Buffer GHC.IO.Device GHC.IO.BufferedIO GHC.IO.FD GHC.IO.Exception GHC.IO.Encoding GHC.IO.Encoding.Latin1 GHC.IO.Encoding.UTF8 GHC.IO.Encoding.UTF16 GHC.IO.Encoding.UTF32 GHC.IO.Encoding.Types GHC.IO.Encoding.Iconv GHC.IO.Encoding.CodePage GHC.IO.Handle GHC.IO.Handle.Types GHC.IO.Handle.Internals GHC.IO.Handle.FD GHC.IO.Handle.Text GHC.IOBase GHC.Handle GHC.IORef GHC.IOArray GHC.Int GHC.List GHC.Num GHC.PArr GHC.Pack GHC.Ptr GHC.Read GHC.Real GHC.ST GHC.STRef GHC.Show GHC.Stable GHC.Storable GHC.TopHandler GHC.Unicode GHC.Weak GHC.Word System.Timeout System.Event Control.Applicative Control.Arrow Control.Category Control.Concurrent Control.Concurrent.Chan Control.Concurrent.MVar Control.Concurrent.QSem Control.Concurrent.QSemN Control.Concurrent.SampleVar Control.Exception Control.Exception.Base Control.OldException Control.Monad Control.Monad.Fix Control.Monad.Instances Control.Monad.ST Control.Monad.ST.Lazy Control.Monad.ST.Strict Data.Bits Data.Bool Data.Char Data.Complex Data.Dynamic Data.Either Data.Eq Data.Data Data.Fixed Data.Foldable Data.Function Data.Functor Data.HashTable Data.IORef Data.Int Data.Ix Data.List Data.Maybe Data.Monoid Data.Ord Data.Ratio Data.STRef Data.STRef.Lazy Data.STRef.Strict Data.String Data.Traversable Data.Tuple Data.Typeable Data.Unique Data.Version Data.Word Debug.Trace Foreign Foreign.C Foreign.C.Error Foreign.C.String Foreign.C.Types Foreign.ForeignPtr Foreign.Marshal Foreign.Marshal.Alloc Foreign.Marshal.Array Foreign.Marshal.Error Foreign.Marshal.Pool Foreign.Marshal.Utils Foreign.Ptr Foreign.StablePtr Foreign.Storable Numeric Prelude System.Console.GetOpt System.CPUTime System.Environment System.Exit System.IO System.IO.Error System.IO.Unsafe System.Info System.Mem System.Mem.StableName System.Mem.Weak System.Posix.Internals System.Posix.Types Text.ParserCombinators.ReadP Text.ParserCombinators.ReadPrec Text.Printf Text.Read Text.Read.Lex Text.Show Text.Show.Functions Unsafe.Coerce System.Event.Array System.Event.Clock System.Event.Control System.Event.EPoll System.Event.IntMap System.Event.Internal System.Event.KQueue System.Event.Manager System.Event.PSQ System.Event.Poll System.Event.Thread System.Event.Unique
libraries/base_dist-install_HIDDEN_MODULES = System.Event.Array System.Event.Clock System.Event.Control System.Event.EPoll System.Event.IntMap System.Event.Internal System.Event.KQueue System.Event.Manager System.Event.PSQ System.Event.Poll System.Event.Thread System.Event.Unique
libraries/base_dist-install_SYNOPSIS =Basic libraries
libraries/base_dist-install_HS_SRC_DIRS = .
libraries/base_dist-install_DEPS = ghc-prim-0.2.0.0 integer-gmp-0.2.0.3 rts-1.0
libraries/base_dist-install_DEP_NAMES = ghc-prim integer-gmp rts
libraries/base_dist-install_INCLUDE_DIRS = include
libraries/base_dist-install_INCLUDES = HsBase.h
libraries/base_dist-install_INSTALL_INCLUDES = HsBase.h HsBaseConfig.h EventConfig.h WCsubst.h consUtils.h Typeable.h
libraries/base_dist-install_EXTRA_LIBRARIES = 
libraries/base_dist-install_EXTRA_LIBDIRS = 
libraries/base_dist-install_C_SRCS  = cbits/PrelIOUtils.c cbits/WCsubst.c cbits/Win32Utils.c cbits/consUtils.c cbits/iconv.c cbits/inputReady.c cbits/selectUtils.c cbits/primFloat.c
libraries/base_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/base/cbits/*.cmm)))
libraries/base_dist-install_DATA_FILES = 
libraries/base_dist-install_HC_OPTS = -package-name base -XMagicHash -XExistentialQuantification -XRank2Types -XScopedTypeVariables -XUnboxedTuples -XForeignFunctionInterface -XUnliftedFFITypes -XDeriveDataTypeable -XGeneralizedNewtypeDeriving -XFlexibleInstances -XStandaloneDeriving -XPatternGuards -XEmptyDataDecls -XNoImplicitPrelude -XCPP
libraries/base_dist-install_CC_OPTS = 
libraries/base_dist-install_CPP_OPTS = -DOPTIMISE_INTEGER_GCD_LCM
libraries/base_dist-install_LD_OPTS = 
libraries/base_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/base_dist-install_DEP_CC_OPTS = 
libraries/base_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/base_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/base_dist-install_DEP_LD_OPTS = 
libraries/base_dist-install_BUILD_GHCI_LIB = YES
