libraries/containers_dist-install_VERSION = 0.4.0.0
libraries/containers_dist-install_MODULES = Data.Graph Data.Sequence Data.Tree Data.IntMap Data.IntSet Data.Map Data.Set
libraries/containers_dist-install_HIDDEN_MODULES = 
libraries/containers_dist-install_SYNOPSIS =Assorted concrete container types
libraries/containers_dist-install_HS_SRC_DIRS = .
libraries/containers_dist-install_DEPS = array-0.3.0.2 base-4.3.1.0
libraries/containers_dist-install_DEP_NAMES = array base
libraries/containers_dist-install_INCLUDE_DIRS = include
libraries/containers_dist-install_INCLUDES = 
libraries/containers_dist-install_INSTALL_INCLUDES = 
libraries/containers_dist-install_EXTRA_LIBRARIES = 
libraries/containers_dist-install_EXTRA_LIBDIRS = 
libraries/containers_dist-install_C_SRCS  = 
libraries/containers_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/containers/cbits/*.cmm)))
libraries/containers_dist-install_DATA_FILES = 
libraries/containers_dist-install_HC_OPTS = -fregs-graph -O2 -XDeriveDataTypeable -XMagicHash -XRank2Types -XCPP
libraries/containers_dist-install_CC_OPTS = 
libraries/containers_dist-install_CPP_OPTS = 
libraries/containers_dist-install_LD_OPTS = 
libraries/containers_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/containers_dist-install_DEP_CC_OPTS = 
libraries/containers_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/containers_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/containers_dist-install_DEP_LD_OPTS = 
libraries/containers_dist-install_BUILD_GHCI_LIB = YES
