libraries/bin-package-db_dist-boot_VERSION = 0.0.0.0
libraries/bin-package-db_dist-boot_MODULES = Distribution.InstalledPackageInfo.Binary
libraries/bin-package-db_dist-boot_HIDDEN_MODULES = 
libraries/bin-package-db_dist-boot_SYNOPSIS =A binary format for the package database
libraries/bin-package-db_dist-boot_HS_SRC_DIRS = .
libraries/bin-package-db_dist-boot_DEPS = Cabal-1.10.1.0 base-4.3.1.0 ghc-binary-0.5.0.2
libraries/bin-package-db_dist-boot_DEP_NAMES = Cabal base ghc-binary
libraries/bin-package-db_dist-boot_INCLUDE_DIRS = 
libraries/bin-package-db_dist-boot_INCLUDES = 
libraries/bin-package-db_dist-boot_INSTALL_INCLUDES = 
libraries/bin-package-db_dist-boot_EXTRA_LIBRARIES = 
libraries/bin-package-db_dist-boot_EXTRA_LIBDIRS = 
libraries/bin-package-db_dist-boot_C_SRCS  = 
libraries/bin-package-db_dist-boot_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/bin-package-db/cbits/*.cmm)))
libraries/bin-package-db_dist-boot_DATA_FILES = 
libraries/bin-package-db_dist-boot_HC_OPTS = -XCPP
libraries/bin-package-db_dist-boot_CC_OPTS = 
libraries/bin-package-db_dist-boot_CPP_OPTS = 
libraries/bin-package-db_dist-boot_LD_OPTS = 
libraries/bin-package-db_dist-boot_DEP_INCLUDE_DIRS = '/usr/lib/ghc-7.0.3/bytestring-0.9.1.10/include' '/usr/lib/ghc-7.0.3/process-1.0.1.5/include' '/usr/lib/ghc-7.0.3/directory-1.1.0.0/include' '/usr/lib/ghc-7.0.3/unix-2.4.2.0/include' '/usr/lib/ghc-7.0.3/old-time-1.0.0.6/include' '/usr/lib/ghc-7.0.3/base-4.3.1.0/include' '/usr/lib/ghc-7.0.3/include' '/usr/lib/ghc-7.0.3/include'
libraries/bin-package-db_dist-boot_DEP_CC_OPTS = 
libraries/bin-package-db_dist-boot_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-binary/dist-boot/build' '/usr/lib/ghc-7.0.3/bytestring-0.9.1.10' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/Cabal/dist-boot/build' '/usr/lib/ghc-7.0.3/process-1.0.1.5' '/usr/lib/ghc-7.0.3/pretty-1.0.1.2' '/usr/lib/ghc-7.0.3/directory-1.1.0.0' '/usr/lib/ghc-7.0.3/unix-2.4.2.0' '/usr/lib/ghc-7.0.3/old-time-1.0.0.6' '/usr/lib/ghc-7.0.3/old-locale-1.0.0.2' '/usr/lib/ghc-7.0.3/filepath-1.2.0.0' '/usr/lib/ghc-7.0.3/containers-0.4.0.0' '/usr/lib/ghc-7.0.3/array-0.3.0.2' '/usr/lib/ghc-7.0.3/base-4.3.1.0' '/usr/lib/ghc-7.0.3/integer-gmp-0.2.0.3' '/usr/lib/ghc-7.0.3/ghc-prim-0.2.0.0' '/usr/lib/ghc-7.0.3' '/usr/lib/ghc-7.0.3'
libraries/bin-package-db_dist-boot_DEP_EXTRA_LIBS = rt util dl gmp m rt dl
libraries/bin-package-db_dist-boot_DEP_LD_OPTS = 
libraries/bin-package-db_dist-boot_BUILD_GHCI_LIB = YES
