libraries/bin-package-db_dist-install_VERSION = 0.0.0.0
libraries/bin-package-db_dist-install_MODULES = Distribution.InstalledPackageInfo.Binary
libraries/bin-package-db_dist-install_HIDDEN_MODULES = 
libraries/bin-package-db_dist-install_SYNOPSIS =A binary format for the package database
libraries/bin-package-db_dist-install_HS_SRC_DIRS = .
libraries/bin-package-db_dist-install_DEPS = Cabal-1.10.1.0 base-4.3.1.0 ghc-binary-0.5.0.2
libraries/bin-package-db_dist-install_DEP_NAMES = Cabal base ghc-binary
libraries/bin-package-db_dist-install_INCLUDE_DIRS = 
libraries/bin-package-db_dist-install_INCLUDES = 
libraries/bin-package-db_dist-install_INSTALL_INCLUDES = 
libraries/bin-package-db_dist-install_EXTRA_LIBRARIES = 
libraries/bin-package-db_dist-install_EXTRA_LIBDIRS = 
libraries/bin-package-db_dist-install_C_SRCS  = 
libraries/bin-package-db_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/bin-package-db/cbits/*.cmm)))
libraries/bin-package-db_dist-install_DATA_FILES = 
libraries/bin-package-db_dist-install_HC_OPTS = -XCPP
libraries/bin-package-db_dist-install_CC_OPTS = 
libraries/bin-package-db_dist-install_CPP_OPTS = 
libraries/bin-package-db_dist-install_LD_OPTS = 
libraries/bin-package-db_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/bytestring/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/process/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/bin-package-db_dist-install_DEP_CC_OPTS = 
libraries/bin-package-db_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-binary/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/bytestring/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/Cabal/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/process/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/pretty/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-locale/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/filepath/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/bin-package-db_dist-install_DEP_EXTRA_LIBS = rt util dl pthread gmp m rt dl
libraries/bin-package-db_dist-install_DEP_LD_OPTS = 
libraries/bin-package-db_dist-install_BUILD_GHCI_LIB = YES
