libraries/haskell98_dist-install_VERSION = 1.1.0.1
libraries/haskell98_dist-install_MODULES = Array CPUTime Char Complex Directory IO Ix List Locale Maybe Monad Random Ratio System Time Bits CError CForeign CString CTypes ForeignPtr Int MarshalAlloc MarshalArray MarshalError MarshalUtils Ptr StablePtr Storable Word
libraries/haskell98_dist-install_HIDDEN_MODULES = 
libraries/haskell98_dist-install_SYNOPSIS =Compatibility with Haskell 98
libraries/haskell98_dist-install_HS_SRC_DIRS = .
libraries/haskell98_dist-install_DEPS = array-0.3.0.2 base-4.3.1.0 directory-1.1.0.0 old-locale-1.0.0.2 old-time-1.0.0.6 process-1.0.1.5 random-1.0.0.3
libraries/haskell98_dist-install_DEP_NAMES = array base directory old-locale old-time process random
libraries/haskell98_dist-install_INCLUDE_DIRS = 
libraries/haskell98_dist-install_INCLUDES = 
libraries/haskell98_dist-install_INSTALL_INCLUDES = 
libraries/haskell98_dist-install_EXTRA_LIBRARIES = 
libraries/haskell98_dist-install_EXTRA_LIBDIRS = 
libraries/haskell98_dist-install_C_SRCS  = 
libraries/haskell98_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/haskell98/cbits/*.cmm)))
libraries/haskell98_dist-install_DATA_FILES = 
libraries/haskell98_dist-install_HC_OPTS = 
libraries/haskell98_dist-install_CC_OPTS = 
libraries/haskell98_dist-install_CPP_OPTS = 
libraries/haskell98_dist-install_LD_OPTS = 
libraries/haskell98_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/time/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/process/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/haskell98_dist-install_DEP_CC_OPTS = 
libraries/haskell98_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/random/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/time/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/process/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/directory/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-locale/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/filepath/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/haskell98_dist-install_DEP_EXTRA_LIBS = rt util dl pthread gmp m rt dl
libraries/haskell98_dist-install_DEP_LD_OPTS = 
libraries/haskell98_dist-install_BUILD_GHCI_LIB = YES
