libraries/haskell2010_dist-install_VERSION = 1.0.0.0
libraries/haskell2010_dist-install_MODULES = Data.Array Data.Char Data.Complex System.IO System.IO.Error Data.Ix Data.List Data.Maybe Control.Monad Data.Ratio System.Environment System.Exit Numeric Prelude Data.Int Data.Word Data.Bits Foreign Foreign.Ptr Foreign.ForeignPtr Foreign.StablePtr Foreign.Storable Foreign.C Foreign.C.Error Foreign.C.String Foreign.C.Types Foreign.Marshal Foreign.Marshal.Alloc Foreign.Marshal.Array Foreign.Marshal.Error Foreign.Marshal.Utils
libraries/haskell2010_dist-install_HIDDEN_MODULES = 
libraries/haskell2010_dist-install_SYNOPSIS =Compatibility with Haskell 2010
libraries/haskell2010_dist-install_HS_SRC_DIRS = .
libraries/haskell2010_dist-install_DEPS = array-0.3.0.2 base-4.3.1.0 ghc-prim-0.2.0.0
libraries/haskell2010_dist-install_DEP_NAMES = array base ghc-prim
libraries/haskell2010_dist-install_INCLUDE_DIRS = 
libraries/haskell2010_dist-install_INCLUDES = 
libraries/haskell2010_dist-install_INSTALL_INCLUDES = 
libraries/haskell2010_dist-install_EXTRA_LIBRARIES = 
libraries/haskell2010_dist-install_EXTRA_LIBDIRS = 
libraries/haskell2010_dist-install_C_SRCS  = 
libraries/haskell2010_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/haskell2010/cbits/*.cmm)))
libraries/haskell2010_dist-install_DATA_FILES = 
libraries/haskell2010_dist-install_HC_OPTS = -XPackageImports -XCPP
libraries/haskell2010_dist-install_CC_OPTS = 
libraries/haskell2010_dist-install_CPP_OPTS = 
libraries/haskell2010_dist-install_LD_OPTS = 
libraries/haskell2010_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/haskell2010_dist-install_DEP_CC_OPTS = 
libraries/haskell2010_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/haskell2010_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/haskell2010_dist-install_DEP_LD_OPTS = 
libraries/haskell2010_dist-install_BUILD_GHCI_LIB = YES
