libraries/directory_dist-install_VERSION = 1.1.0.0
libraries/directory_dist-install_MODULES = System.Directory
libraries/directory_dist-install_HIDDEN_MODULES = 
libraries/directory_dist-install_SYNOPSIS =library for directory handling
libraries/directory_dist-install_HS_SRC_DIRS = .
libraries/directory_dist-install_DEPS = base-4.3.1.0 filepath-1.2.0.0 old-time-1.0.0.6 unix-2.4.2.0
libraries/directory_dist-install_DEP_NAMES = base filepath old-time unix
libraries/directory_dist-install_INCLUDE_DIRS = include
libraries/directory_dist-install_INCLUDES = HsDirectory.h
libraries/directory_dist-install_INSTALL_INCLUDES = HsDirectory.h HsDirectoryConfig.h
libraries/directory_dist-install_EXTRA_LIBRARIES = 
libraries/directory_dist-install_EXTRA_LIBDIRS = 
libraries/directory_dist-install_C_SRCS  = cbits/directory.c
libraries/directory_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/directory/cbits/*.cmm)))
libraries/directory_dist-install_DATA_FILES = 
libraries/directory_dist-install_HC_OPTS = -XCPP -XForeignFunctionInterface
libraries/directory_dist-install_CC_OPTS = 
libraries/directory_dist-install_CPP_OPTS = 
libraries/directory_dist-install_LD_OPTS = 
libraries/directory_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/directory_dist-install_DEP_CC_OPTS = 
libraries/directory_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/unix/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-time/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/old-locale/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/filepath/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/directory_dist-install_DEP_EXTRA_LIBS = rt util dl pthread gmp m rt dl
libraries/directory_dist-install_DEP_LD_OPTS = 
libraries/directory_dist-install_BUILD_GHCI_LIB = YES
