libraries/extensible-exceptions_dist-boot_VERSION = 0.1.1.2
libraries/extensible-exceptions_dist-boot_MODULES = Control.Exception.Extensible
libraries/extensible-exceptions_dist-boot_HIDDEN_MODULES = 
libraries/extensible-exceptions_dist-boot_SYNOPSIS =Extensible exceptions
libraries/extensible-exceptions_dist-boot_HS_SRC_DIRS = .
libraries/extensible-exceptions_dist-boot_DEPS = base-4.3.1.0
libraries/extensible-exceptions_dist-boot_DEP_NAMES = base
libraries/extensible-exceptions_dist-boot_INCLUDE_DIRS = 
libraries/extensible-exceptions_dist-boot_INCLUDES = 
libraries/extensible-exceptions_dist-boot_INSTALL_INCLUDES = 
libraries/extensible-exceptions_dist-boot_EXTRA_LIBRARIES = 
libraries/extensible-exceptions_dist-boot_EXTRA_LIBDIRS = 
libraries/extensible-exceptions_dist-boot_C_SRCS  = 
libraries/extensible-exceptions_dist-boot_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/extensible-exceptions/cbits/*.cmm)))
libraries/extensible-exceptions_dist-boot_DATA_FILES = 
libraries/extensible-exceptions_dist-boot_HC_OPTS = -XCPP -XExistentialQuantification -XDeriveDataTypeable
libraries/extensible-exceptions_dist-boot_CC_OPTS = 
libraries/extensible-exceptions_dist-boot_CPP_OPTS = -DUSE_NEW_EXCEPTIONS
libraries/extensible-exceptions_dist-boot_LD_OPTS = 
libraries/extensible-exceptions_dist-boot_DEP_INCLUDE_DIRS = '/usr/lib/ghc-7.0.3/base-4.3.1.0/include' '/usr/lib/ghc-7.0.3/include' '/usr/lib/ghc-7.0.3/include'
libraries/extensible-exceptions_dist-boot_DEP_CC_OPTS = 
libraries/extensible-exceptions_dist-boot_DEP_LIB_DIRS = '/usr/lib/ghc-7.0.3/base-4.3.1.0' '/usr/lib/ghc-7.0.3/integer-gmp-0.2.0.3' '/usr/lib/ghc-7.0.3/ghc-prim-0.2.0.0' '/usr/lib/ghc-7.0.3' '/usr/lib/ghc-7.0.3'
libraries/extensible-exceptions_dist-boot_DEP_EXTRA_LIBS = gmp m rt dl
libraries/extensible-exceptions_dist-boot_DEP_LD_OPTS = 
libraries/extensible-exceptions_dist-boot_BUILD_GHCI_LIB = YES
