libraries/template-haskell_dist-install_VERSION = 2.5.0.0
libraries/template-haskell_dist-install_MODULES = Language.Haskell.TH.Syntax.Internals Language.Haskell.TH.Syntax Language.Haskell.TH.PprLib Language.Haskell.TH.Ppr Language.Haskell.TH.Lib Language.Haskell.TH.Quote Language.Haskell.TH
libraries/template-haskell_dist-install_HIDDEN_MODULES = 
libraries/template-haskell_dist-install_SYNOPSIS =
libraries/template-haskell_dist-install_HS_SRC_DIRS = .
libraries/template-haskell_dist-install_DEPS = base-4.3.1.0 containers-0.4.0.0 pretty-1.0.1.2
libraries/template-haskell_dist-install_DEP_NAMES = base containers pretty
libraries/template-haskell_dist-install_INCLUDE_DIRS = 
libraries/template-haskell_dist-install_INCLUDES = 
libraries/template-haskell_dist-install_INSTALL_INCLUDES = 
libraries/template-haskell_dist-install_EXTRA_LIBRARIES = 
libraries/template-haskell_dist-install_EXTRA_LIBDIRS = 
libraries/template-haskell_dist-install_C_SRCS  = 
libraries/template-haskell_dist-install_CMM_SRCS  = $(addprefix cbits/,$(notdir $(wildcard libraries/template-haskell/cbits/*.cmm)))
libraries/template-haskell_dist-install_DATA_FILES = 
libraries/template-haskell_dist-install_HC_OPTS = -package-name template-haskell -XMagicHash -XPatternGuards -XPolymorphicComponents -XDeriveDataTypeable -XTypeSynonymInstances
libraries/template-haskell_dist-install_CC_OPTS = 
libraries/template-haskell_dist-install_CPP_OPTS = 
libraries/template-haskell_dist-install_LD_OPTS = 
libraries/template-haskell_dist-install_DEP_INCLUDE_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/include' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/include' '/home/khs/documents/project/test5/ghc-7.0.3/includes' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/template-haskell_dist-install_DEP_CC_OPTS = 
libraries/template-haskell_dist-install_DEP_LIB_DIRS = '/home/khs/documents/project/test5/ghc-7.0.3/libraries/pretty/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/containers/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/array/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/base/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/integer-gmp/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/libraries/ghc-prim/dist-install/build' '/home/khs/documents/project/test5/ghc-7.0.3/rts/dist/build' '/home/khs/documents/project/test5/ghc-7.0.3/libffi/dist-install/build'
libraries/template-haskell_dist-install_DEP_EXTRA_LIBS = gmp m rt dl
libraries/template-haskell_dist-install_DEP_LD_OPTS = 
libraries/template-haskell_dist-install_BUILD_GHCI_LIB = YES
